namespace DXPlus
{
    public enum BlockArrowShapes
    {
        RightArrow,
        LeftArrow,
        UpArrow,
        DownArrow,
        LeftRightArrow,
        UpDownArrow,
        QuadArrow,
        LeftRightUpArrow,
        BentArrow,
        UturnArrow,
        LeftUpArrow,
        BentUpArrow,
        CurvedRightArrow,
        CurvedLeftArrow,
        CurvedUpArrow,
        CurvedDownArrow,
        StripedRightArrow,
        NotchedRightArrow,
        HomePlate,
        Chevron,
        RightArrowCallout,
        DownArrowCallout,
        LeftArrowCallout,
        UpArrowCallout,
        LeftRightArrowCallout,
        QuadArrowCallout,
        CircularArrow
    };
}