using System.Xml.Serialization;

namespace DXPlus;

/// <summary>
/// Specifies the characters which may be used to fill in the space created
/// by a tab which ends at this custom tab stop. The chosen character shall
/// be repeated as required to completely fill the tab spacing generated by the tab character.
/// </summary>
public enum TabStopLeader
{
    /// <summary>
    /// Leader character is a dot.
    /// </summary>
    [XmlAttribute("dot")] Dot,

    /// <summary>
    /// Leader character is a heavy solid line.
    /// </summary>
    [XmlAttribute("heavy")] Solid,

    /// <summary>
    /// Leader character is a hyphen
    /// </summary>
    [XmlAttribute("hyphen")] Hyphen,

    /// <summary>
    /// Leader character is a centered dot.
    /// </summary>
    [XmlAttribute("middleDot")] CenteredDot,

    /// <summary>
    /// No leader character
    /// </summary>
    [XmlAttribute("none")] None,

    /// <summary>
    /// Leader character is an underscore
    /// </summary>
    [XmlAttribute("underscore")] Underscore
}