name: Build and Publish DXPlus library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release
    - name: Test
      working-directory: ./tests/DXPlus.Tests
      run: dotnet test --verbosity normal
    - name: Pack
      working-directory: ./src
      run: dotnet pack DXPlus.csproj --output nuget-packages --configuration Release
    - name: Push to NuGet
      working-directory: ./src
      run: dotnet nuget push nuget-packages/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
